name: Release new version

on:
  push:
    tags:
      - 'release-*'
    branches:
      - master

jobs:
  Release-pipeline:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: pip install poetry pre-commit && pre-commit install
      - name: Format
        run: pre-commit run --all-files
      - name: Poetry install
        run: "cd backup_to_harddrive && poetry lock && poetry install"
      - name: Pylint
        run: "cd backup_to_harddrive && poetry run pylint src tests --msg-template=\"{path}:{line}:{column}: {msg_id} ({symbol}) {msg}\""
      - name: Code coverage
        run: cd backup_to_harddrive && poetry run pytest --cov=.
      - name: Build package
        run: cd backup_to_harddrive && poetry build
      # TODO: #12: Bump version but then we have to commit and merge to master. Also make sure that the new version match the tag.
      # - name: Bump version
      #   run: cd backup_to_harddrive && poetry version patch
      - name: Publish package
        run: cd backup_to_harddrive && poetry publish --username __token__  --password ${{ secrets.PYPI_TOKEN }}
